Dataframes : when you combine multiple series a dataframe is formed

In [1]:
import numpy as np
import pandas as pd

creating a dataframe

In [7]:
data={
    "Name":["jhon","anna","linda"],
    "Age":[28,29,30],
    "City":["nyc","dakota","berlin"],
    "Salary":[65000,75000,85000],
   
}
labels=[1,2,3]
df=pd.DataFrame(data,index=labels)
df

    Name  Age    City  Salary
1   jhon   28     nyc   65000
2   anna   29  dakota   75000
3  linda   30  berlin   85000

dataframe using list

here as compared to headers in dictionary were already defined where as using list the column names or the names ofdetails were set to default

In [17]:
data_list=[
    ["john",28,"newyork",65000],
    ["anna",29,"dakota",75000],
    ["linda",30,"berlin",85000]
]
labels=[1,2,3]
columns=["name","age","city","salary"]
df2=pd.DataFrame(data_list,index=labels,columns=columns)
df

    name  age     city  salary
1   john   28  newyork   65000
2   anna   29   dakota   75000
3  linda   30   berlin   85000

In [22]:
df2[['name','city']]

    name     city
1   john  newyork
2   anna   dakota
3  linda   berlin

creating a new column : experience

In [23]:
df2["experience"]=["doctor","engineer","businessman"]

In [24]:
df2

    name  age     city  salary   experience
1   john   28  newyork   65000       doctor
2   anna   29   dakota   75000     engineer
3  linda   30   berlin   85000  businessman

removing a column

In [30]:
df2.drop('experience',axis=1,inplace=True)

inplace : after dropping the column the original df is intact and a copy of it is shown so to edit the original df we use inplace to finalize the deletion

In [31]:
df2

    name  age     city  salary
1   john   28  newyork   65000
2   anna   29   dakota   75000
3  linda   30   berlin   85000

selecting rows --> data_frame.loc[column_no.]
               
               -->data_frame.iloc[index]

In [33]:
df2.loc[1]

name         john
age            28
city      newyork
salary      65000
Name: 1, dtype: object

selecting subsets of rows and columns

In [36]:
df2.loc[[1,2]][["city","salary"]]

      city  salary
1  newyork   65000
2   dakota   75000

In [37]:
df2.loc[[2,3]][["name","age"]]

    name  age
2   anna   29
3  linda   30

conditional selections

In [39]:
df2

    name  age     city  salary
1   john   28  newyork   65000
2   anna   29   dakota   75000
3  linda   30   berlin   85000

only those people whose age is above 28

In [40]:
df2[df2["age"]>28]

    name  age    city  salary
2   anna   29  dakota   75000
3  linda   30  berlin   85000

only the people who are from berlin

In [41]:
df2[df2["city"]=="berlin"]

    name  age    city  salary
3  linda   30  berlin   85000

In [44]:
df2[(df2["age"]>28) & (df2["city"]=="berlin")]

    name  age    city  salary
3  linda   30  berlin   85000