missing data : 

removing missing data

filling the missing data

In [ ]:
import numpy as np
import pandas as pd

np.nan--> null value

In [ ]:
data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [1, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}

In [ ]:
df=pd.DataFrame(data)
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

df.isna() --> gives value as true for a null value

In [ ]:
df.isna()

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

df.isna().sum() --> gives total no. of null values in each col

In [ ]:
df.isna().sum()

A    1
B    0
C    2
D    3
dtype: int64

df.isna().any() --> if theres is any missing value in each column

In [ ]:
df.isna().any()

A     True
B    False
C     True
D     True
dtype: bool

In [ ]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

removing missing data --> works on the basis of rows

df.dropna() --> drops the rows containing null values

In [ ]:
df.dropna()

     A  B    C    D
0  1.0  1  1.0  1.0

df.dropna(thresh=3) --> threshold set to 3(the rows must contain atleast thresh non null values )

In [ ]:
df.dropna(thresh=1)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

filling missing data

In [ ]:
df.fillna(0)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

In [ ]:
values={'A':0,'B':100,'C':300,'D':400}
df.fillna(value=values)

     A  B      C      D
0  1.0  1    1.0    1.0
1  2.0  2    2.0  400.0
2  0.0  3    3.0  400.0
3  4.0  4  300.0  400.0
4  5.0  5  300.0    5.0

df.fillna(df.mean()) --> fills null value with mean of all values

In [ ]:
df.fillna(df.mean())

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  3.0
2  3.0  3  3.0  3.0
3  4.0  4  2.0  3.0
4  5.0  5  2.0  5.0